### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by gotojeffray** [gotojeffray/SEBC#1]

**Comment by gotojeffray** [comment]
1) We've got a ansible playbook for installing CM, so I just need to modify few configurations to make it work.
2) We've been using postgresql for years, so setting up postgresql server and replication won't be a problem for me.

**Comment by gotojeffray** [comment]
I've installed version 5.8.2 on all nodes, but found CM was distributing 5.8.3?

**Comment by gotojeffray** [comment]
1) Use /etc/hosts to resolve the dns.
2) stop and start ntpd to solve clock offset.

**Comment by mfernest** [comment]
You should probably practice with MySQL. You won't have your choice of database server for the challenge.

**Comment by mfernest** [comment]
`1_preinstall.md` - You can delete ipv6 configurations from any CDH nodes. It is not supported.
`2_replica_working.md` - good. Did you name a database `metastore.DBS`? I didn't think MySQL would tolerate a . in a database name.
`3_cm_installed.png` - good.
`4_local_repo_httpd.png` & `4_local_repo.png` 🏆 

Good work.

**Comment by gotojeffray** [comment]
'metastore' is the DB name of hive metastore. I run a command like this 'select * from "DBS" ', but it's a postgresql syntax. At last, I found there is no need to add quote sign in mysql syntax.
