### ISSUE TITLE
Install CM

### ISSUE THREAD

**Issue by gotojeffray** [gotojeffray/SEBC#10]

**Comment by gotojeffray** [comment]
1) I must run this first
mysql> grant all on scm.* to 'root'@'cdh01.gotojeffray.nz' identified by 'root' with grant option;
Query OK, 0 rows affected (0.00 sec)


2) Can't create database 'scm'; 
database existsmysql> drop database  scm;
Query OK, 0 rows affected (0.00 sec)

3) mysql> drop user  scm;
Query OK, 0 rows affected (0.00 sec)

4) Still got an error:
 You are not allowed to create a user with GRANT

5) grant all PRIVILEGES  on *.* to 'root'@'cdh01.gotojeffray.nz' identified by 'root' with grant option;

solved my problem.

**Comment by mfernest** [comment]
You could have removed `WITH GRANT OPTION` also with no loss of capability. This approach is less brute-force than granting privileges to the entire server to honor the GRANT.

**Comment by mfernest** [comment]
👍
