### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by gotojeffray** [gotojeffray/SEBC#3]

**Comment by gotojeffray** [comment]
CM url:  http://52.221.239.59:7180/

**Comment by mfernest** [comment]
`0_replication.md` - you could try an interface that doesn't require a cluster-to-cluster node mapping, such as webhdfs.
`1_terasort_tests.md` - a barebones report, but ok. You could include the job transcript here so you have one for reference.
`2_snapshot_test.md` - you left out the attempt the delete a snapshot directory
`3_HDFS_HA.png` - ok
`4_CM_users.png` - ok

INC
